services:

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zk
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    networks:
      - local-network

    ## Apache Kafka
  kafka:
    image: bitnami/kafka:3.6
    container_name: events-transactions-wallets
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      -  KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://host.docker.internal:29092
      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper
    networks:
      - local-network

  ## Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - 8089:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      # O Kafka UI se conecta ao Kafka usando o nome do serviço interno
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - local-network
  ## Redis
  redis:
    image: redis:7.2
    container_name: redis-cache-wallets
    ports:
      - "6379:6379"
    networks:
      - local-network
    command: [ "redis-server", "--appendonly", "yes" ]

## Postgres Databases
  postgres:
    image: postgres:17.5
    container_name: wallet-bank
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - local-network

  ## PG Admin
  pgadmin:
    image: dpage/pgadmin4:9.5
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: carlos@viaresults.com.br
      PGADMIN_DEFAULT_PASSWORD: cbgomes
    ports:
      - 8888:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - local-network

## LocalStack
  localstack:
    image: localstack/localstack:3
    container_name: localstack-wallet-assignment
    environment:
      SERVICES: sns,sqs,s3,lambda,dynamodb,apigateway,cloudwatch,logs,ec2,ses
      LOCALSTACK_API_GATEWAY_FORCE_HTTP1: true
      DEBUG: 1
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY-}
      EDGE_PORT: 4566
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"   # Endpoint principal
      - "4510-4559:4510-4559"
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local-network

  ## Microservices
  ms-analysis-engine:
    image: carlosbarbosafilho/ms-analysis-engine:0.0.1
    environment:
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
    build:
      context: .
      dockerfile: Dockerfile
      target: ms-analysis-engine
    ports:
      - "8086:8086"
    networks:
      - local-network

  ms-notification:
    image: carlosbarbosafilho/ms-notification:0.0.1
    environment:
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
    build:
      context: .
      dockerfile: Dockerfile
      target: ms-notification
    ports:
      - "8084:8084"
    networks:
      - local-network

  ms-clients:
    image: carlosbarbosafilho/ms-clients:0.0.1
    environment:
        - AWS_REGION=us-east-1
        - AWS_ENDPOINT_URL=http://localstack:4566
    build:
      context: .
      dockerfile: Dockerfile
      target: ms-clients
    ports:
      - "8081:8081"
    networks:
      - local-network

  ms-wallets:
    image: carlosbarbosafilho/ms-wallets:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
      target: ms-wallets
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - local-network

  ms-transactions:
    image: carlosbarbosafilho/ms-transactions:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
      target: ms-transactions
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    networks:
      - local-network

  api-gateway:
    image: carlosbarbosafilho/gateway:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway
    ports:
      - "8085:8085"
    depends_on:
      - ms-clients
      - ms-wallets
      - ms-transactions
      - ms-notification
    networks:
      - local-network

volumes:
  postgres-data:
  pgadmin-data:
  localstack_data:

networks:
  local-network:
    driver: bridge
    external: true