server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: health ,info,metrics
spring:
  application:
    name: ms-notification
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: cbgomes
        secret-key: cbgomes
      sqs:
        endpoint: http://localstack:4566